### ISSUE TITLE
rename ProviderMetric to MetricSnapshot?

### ISSUE THREAD

**Issue by hpiwowar** [ourresearch/total-impact-core#1]
Wondering if different names would make the meanings of Metrics and ProviderMetric more clear.

Metrics is a list (with metadata) of all metric objects for an item, whereas the ProviderMetric object is the details of a metric value at a given point of time, correct?

How about renaming ProviderMetric to MetricSnapshot?

**Comment by hpiwowar** [comment]
rename ProviderMetric to MetricResponse?  MetricReturn?  MetricGrab?  MetricSnap?  

or something else all together?

**Comment by richard-jones** [comment]
MetricInstance ?  Or move away from Metric altogether?  Measurement?

But, overall, I'm not fussed.

**Comment by hpiwowar** [comment]
Will rename to MetricSnap once the tests all run again.
