### ISSUE TITLE
Entering a DOI should also return tweet statistics for http://dx.doi.org/ with the DOI

### ISSUE THREAD

**Issue by ethanwhite** [ourresearch/total-impact-core#101]
To replicate: Enter a DOI into the web app (the one I used was 10.1890/11-2177.1) as one object and the same DOI as part of the standard URL as another object (so, I used http://dx.doi.org/10.1890/11-2177.1). The result is two separate objects with different (at least in this case) Twitter data (both different numbers of tweets and different tweets). The result is the same if you do the DOI in one search and the URL separately in another.

Expected behavior: I would expect these two forms of the DOI to be recognized as the same research object and the combined results reported under the Articles section.

**Comment by hpiwowar** [comment]
Ethan, thanks for the bug report.  You are definitely right that it should take dois in this format and handle them properly, and it doesn't do this right now.  In our queue to fix.  Thanks again!
