### ISSUE TITLE
Report how many unique items an API has left before hitting 1000 limit

### ISSUE THREAD

**Issue by jasonpriem** [ourresearch/total-impact-core#108]
The nicest approach is to include a field in the HTTP header. If it's easier, we could instead just make an API endpoint that tells you how many unique products are left when queried with a user's key.

When we ship this, notify Abhitesh.

**Comment by jasonpriem** [comment]
Also notify Eamonn when we ship it.

**Comment by hpiwowar** [comment]
Closing until we can gauge interest and urgency.  created as a suggestion on uservoice: http://feedback.impactstory.org/forums/166950-general/suggestions/4302925-return-quota-status-in-api-response-header

**Comment by jasonpriem** [comment]
yup, this is just how we should do these. well done.
