### ISSUE TITLE
PMID and DOI's are not linked into a single record.

### ISSUE THREAD

**Issue by phayes** [ourresearch/total-impact-core#118]
Compare the following:

http://impactstory.org/item/doi/10.1136/bmj.f3037

and

http://impactstory.org/item/pmid/23682040

These are the same article, yet have vastly different statistics depending on if you query by PMID or by DOI.

**Comment by hpiwowar** [comment]
Patrick, belated thanks for this bug report.

We normally handle this case properly, but it looks like you found a bug.

We aren't getting the doi from PubMed from the pmid, even though we should be (it is in PubMed's XML: http://www.ncbi.nlm.nih.gov/pubmed/23682040?report=xml&format=text)

will prioritize and look into a fix.

Thanks for the bug report!
