### ISSUE TITLE
Dryad Provider _extract_aliases not working

### ISSUE THREAD

**Issue by richard-jones** [ourresearch/total-impact-core#12]
The _extract_aliases method in the Dryad provider is failing its test.  A couple of comments on this:

There is a block of code which extracts the details from the HTML:

```
for arr in arrs:
        # FIXME: this looks fragile.  Dependent on order of attributes
        # in supplied XML
        # FIXME: dc.identifier.uri is not in the arr.attrs, but
        # dc.identifier is.  Is this right or wrong?
        if (u'name', u'dc.identifier.uri') in arr.attrs:
            identifiers += [("URL", arr.str.text)]
        elif (u'name', u'dc.title') in arr.attrs:
            identifiers += [("TITLE", arr.str.text)]
```

I have added FIXMEs covering the following issues:

1/ The code looks fragile, as it is contingent on the ordering of the HTML elements.  That is, if name and dc.identifier.uri appear reversed, then this code will fail; e.g.

```
>>> atts = [(u'dc.identifier', u'name')]
>>> (u'name', u'dc.identifier') in atts
False
```

Perhaps we can guarantee that the BeautifulSoup library will always return things in the correct order, but I don't know.

2/ the test is failing because the "arr" variable contains dc.identifier not dc.identifier.uri - not sure whether this is a bug in the test or the code, so haven't fixed it.

**Comment by hpiwowar** [comment]
The test seems to be passing for me.  Is it still breaking for you, Richard?

I'll make the code not as sensitive to the ordering of the elements, good point.

**Comment by richard-jones** [comment]
Looks like it is working, yes - all the tests are passing this morning.  I'll leave it to you, Heather, to close when you are happy with the element ordering fix.
