### ISSUE TITLE
problem in articles with diacritical marks (when imported from Google Scholar)

### ISSUE THREAD

**Issue by jalperin** [ourresearch/total-impact-core#120]
Have a look at my profile (expand the articles with no metrics): http://impactstory.org/JuanPabloAlperin

Both in the titles and in the journal names

**Comment by hpiwowar** [comment]
Thanks for this bug report, @jalperin!  

This has now been fixed (commit 3ea37b579152629c776849015795dd4d1f82c358).

You'll have to delete the old products from your profile and reimport your google scholar bibtex, but then everything should display properly.  Thanks for your patience as we improve our unicode support!
