### ISSUE TITLE
No Scopus citations shown for an article with >100 WoS citations

### ISSUE THREAD

**Issue by jasonpriem** [ourresearch/total-impact-core#129]
Seems likely Scopus has some and we are missing them.

Title: Onset of convection in a gravitationally unstable diffusive boundary layer in porous media
Author(s): Riaz, A; Hesse, M; Tchelepi, HA; et al.
Source: Journal of Fluid Mechanics Volume: 548 Pages: 87-111 Published: FEB 10 2006 
Times Cited: 168 
DOI: 10.1017/S0022112005007494

Notify Hesse if we get it fixed.

**Comment by herrison** [comment]
Scopus has 176 citations

**Comment by jasonpriem** [comment]
Excellent, thanks Mike!

**Comment by herrison** [comment]
Any time!

**Comment by hpiwowar** [comment]
Followed up with Hesse.
