### ISSUE TITLE
Dryad Provider _extract_stats regexes reorganise

### ISSUE THREAD

**Issue by richard-jones** [ourresearch/total-impact-core#13]
the _extract_stats regexes are all compiled each time the method is run, which is an unnecessary overhead.  They should all be compiled in the provider's constructor, so they only get done once when the watcher is started.  I can do this myself later when I get to it, if no-one beats me there!

**Comment by hpiwowar** [comment]
Good point.  I'm happy to do it... I'm pretty Dryad provider focused this sprint :)
