### ISSUE TITLE
Should aliases dict match identifier field in BibJSON?

### ISSUE THREAD

**Issue by hpiwowar** [ourresearch/total-impact-core#16]
Looks like BibJSON has an "identifier" field that is capturing what our aliases dict is capturing.  Our current format in get_aliases_dict:
{"doi": "10.1186/1758-2946-3-47"}

BibJSON format is a list of dicts
[{"type":"doi","id":"10.1186/1758-2946-3-47"}]

Shall we use BibJSON format instead, to be consistent?

(actually, why does BibJSON use that format?  Are there sometimes more keys in the dict?)

**Comment by hpiwowar** [comment]
actually I'm liking the BibJSON approach as I think about it: when an item has more than one url (as most articles do) we could flag one of them as preferred.  We could use all the urls for collecting usage stats, but then just the preferred one to render a link on our reports.

**Comment by markmacgillivray** [comment]
hmm, interesting. yes, bibjson does it that way because sometimes people provide ID descriptions - by having a dict of key/value pairs, we can allow pretty much anything in future.
