### ISSUE TITLE
Standard way of referring to alias namespaces is required

### ISSUE THREAD

**Issue by richard-jones** [ourresearch/total-impact-core#17]
At the moment Alias namespaces are all declared as strings wherever they are needed in the code.  This is problematic, as it is error prone (both through typos and simply forgetting the specific terms for particular namespaces, not to mention how this affects the use of **kwargs in various constructors).

We should have a central point of contact to get the canonical form of a namespace.  Not sure how this is going to work yet - we could either just have a dictionary of known namespaces, or have a canoicalisation routine which is run by the getters and setters of the alias object at the appropriate time (e.g. upper-case, look up known variants, etc).

Thoughts?

**Comment by hpiwowar** [comment]
I like the canoicalisation routine idea.

**Comment by richard-jones** [comment]
Ok, I will play with this and come up with a solution proposal

**Comment by richard-jones** [comment]
I have done an implementation and checked it in for comment.  It works as follows:

1/ In the Aliases object there is an inner class called Namespaces (which can also be referred to as NS), so that standard namespaces can be referenced statically.  For example, when creating an Alias tuple

```
(Aliases.NS.DOI, "10.1234/journal/blah")
```

2/ All get and set routines (including the constructor) now canonicalise incoming namespaces, so it's less critical that the user of the API know what the canonical versions look like.  For example:

```
my_alias.TIID
my_alias.tiid
```

are the same.

3/ There is a synonyms property of the Aliases object which knows when two namespaces are really the same namespace under a different name.  At the moment it looks like this:

```
synonyms = {
    "DOI" : ["DIGITAL OBJECT IDENTIFIER"],
    "URI" : ["IRI"]
}
```

This means that I can reliably do the following:

```
>>> alias.add_alias("digital object identifier", "10.1234/journal/blah")
>>> alias.doi == "10.1234/journal/blah"
True
```

Leaving this issue open until we've reviewed the proposed solution
