### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by richard-jones** [ourresearch/total-impact-core#34]
Do the error handling

Depends on #33

**Comment by richard-jones** [comment]
Error Mitigation
- Per-error configuration
- Provider re-tries a sensible number of times for the error (use incremental back-off)
- After exceeding configured try times, throws error to error handling

Error Handling:
- what the error was 
  - summary (error type) 
  - and detail (msg dump)
- when it happened
- which item it happened to (+ any other relevant details)
- which provider threw the error

Rate Limiting
- report the rate limit excession
- incremental back-off on re-trying (double the time you wait each time)

**Comment by kevcampb** [comment]
This now exists for metrics. Will generate Error documents in the couch database.

RateLimiting is handled by catching errors from the provider. We treat this just like any other error, but in the config we should really ensure that retry count is -1 (unlimited) and we have exponential falloff.

Will add for aliases, if we can agree on implementation.

**Comment by markmacgillivray** [comment]
Moving to sprint 5 - it has been reopened and is unclear if it is finished.
