### ISSUE TITLE
Is Metrics behaviour correct to update last_requested on construction

### ISSUE THREAD

**Issue by richard-jones** [ourresearch/total-impact-core#35]
In the Metrics object constructor there is the following code (FIXME added by me)

```
# FIXME: is constructing an object synonymous with requesting the data?  Aren't there
# admin functions which might construct this object without "requesting" the data from
# the provider
now = time.time()
for prov_id in self.data['meta'].keys():
    self.data['meta'][prov_id]['last_requested'] = now
```

This suggests that each time the metrics object is constructed, it is for the purposes of new provider metrics being retrieved.  Once there is an admin interface, I don't expect that this will always be the case.  In addition, working with model objects sometimes requires them to be created and manipulated for other reasons (e.g. comparisons with others), which would erroneously set the last_requested properties.

Thoughts?

**Comment by hpiwowar** [comment]
Are we using the last_requested field for anything now?  If not, I'd actually suggest removing it until we implement a use for it.  At that point it will be clear what and when we want it to be updated.

**Comment by richard-jones** [comment]
It's necessary for the queue, I believe.  Mark and I have talked about this, and moved the functionality to a better location, so I will resolve this issue now.
