### ISSUE TITLE
changing metrics.meta to metrics.update_status

### ISSUE THREAD

**Issue by hpiwowar** [ourresearch/total-impact-core#37]
Metrics has a field called meta
and ProviderMetrics has a different field called meta

Metrics.meta actually captures status information about updating and requesting:

'meta': {u'Dryad': {'ignore': False,
                     'last_modified': 1332477064.7848959,
                     'last_requested': 1332477064.783433},
          u'Github': {'ignore': False,
                      'last_modified': 0,
                      'last_requested': 1332477064.783433}}}

I suggest renaming Metrics.meta to Metrics.update_status
(other suggestions are welcome)

Will wait until the system is working end to end with tests to make sure I don't break anything.

**Comment by markmacgillivray** [comment]
the meta object is an exposed object, so is essentially part of the API of things. It provides metadata, regardless of whether that metadata is different for different objects. We could change it, but then will require testing for any calls to it.
