### ISSUE TITLE
update README - successful install on reference system now requires more

### ISSUE THREAD

**Issue by markmacgillivray** [ourresearch/total-impact-core#45]
The latest stage of this software no longer installs on the reference system - Ubuntu 11.10. In order to succeed, you must first 

apt-get install python-lxml

this even on a machine that already had libxslt-dev and libxml2-dev and so on.

**Comment by kevcampb** [comment]
Do you want a .deb made for this software?

**Comment by markmacgillivray** [comment]
not on current requirements. useful consideration for later though.

**Comment by markmacgillivray** [comment]
done.
