### ISSUE TITLE
test_api has a failing test_item_get_success_fakeid

### ISSUE THREAD

**Issue by markmacgillivray** [ourresearch/total-impact-core#49]
the test_api seems to assert equals on a list of object keys, but I think that equality requires order as well, so this cannot be guaranteed to pass as the order of keys in an object is not guaranteed...

**Comment by jasonpriem** [comment]
fixed by casting to sets, then comparing (only works if keys are unique, but they are in this case....good enough)

**Comment by markmacgillivray** [comment]
coolio
