### ISSUE TITLE
Can we delete the /static folder from total-impact-core

### ISSUE THREAD

**Issue by markmacgillivray** [ourresearch/total-impact-core#50]
as the webapp has been separated out, presumably there is no longer anything under /static that we require for the API. Just wanted to check though.

**Comment by hpiwowar** [comment]
We're still going to need it because the api returns either json or html.  To render html we might need to use some of the style sheets etc.

**Comment by markmacgillivray** [comment]
html does not require css though, we would only need css if we care about how it looks, which seems like an odd consideration for an API. However, we can clarify this at the meeting.

**Comment by markmacgillivray** [comment]
discussed, leaving for now
