### ISSUE TITLE
http response caching

### ISSUE THREAD

**Issue by markmacgillivray** [ourresearch/total-impact-core#58]

**Comment by jasonpriem** [comment]
Let's do this a simple as can possibly work--something like the memcached approach on the old codebase, something like 10 lines of code or whatever. We don't need a lot of functionality, and key/val is simple.

**Comment by kevcampb** [comment]
This should now be working on master. 

Code is fairly trivial. Not honouring no-cache or similar, I doubt we'd really want that and it's a lot of code to cover all the variations. We are caching on url as a key, ignoring headers. That might cause some issues for odd providers which return a different result dependent on header values, but will leave that case for now.
