### ISSUE TITLE
Create the test that proves completion of sprint 4

### ISSUE THREAD

**Issue by markmacgillivray** [ourresearch/total-impact-core#61]
the idea is to have a test that runs and proves we have completed the sprint. Create it.

**Comment by jasonpriem** [comment]
I've finished the one that shows the basics of the item api works, along with the metrics queue and backend, and all three providers. I think all we need now is one for the collections.

I suggest that we wait on the more fancy methods in the items api like the comma-separated multiple upload...i mean, they can be in the unit tests, but i think it's overkill to put these and others in the acceptance tests.

**Comment by hpiwowar** [comment]
I added acceptance tests for /collection and /tiid apis.  
Will wait to close this until someone else has a look.

Let's see if it will work to give @jasonpriem a heads up in the comment like this.
