### ISSUE TITLE
Possible bug in Wikipedia metrics code

### ISSUE THREAD

**Issue by richard-jones** [ourresearch/total-impact-core#69]
It looks like the metrics() method of the wikipedia provider doesn't properly deal with multiple aliases.  Not a priority in sprint 4, so ignoring for the time being, and raising this ticket so that we don't forget to look at it later.

**Comment by kevcampb** [comment]
Is this by design? I'd reviewed this and the code now raises a warning if more than 1 DOI alias is present. From what I understand, this will always be the case?

**Comment by kevcampb** [comment]
Noted in PROVIDERS.md
