### ISSUE TITLE
save on error model does not work

### ISSUE THREAD

**Issue by markmacgillivray** [ourresearch/total-impact-core#71]
I am having difficulty making the save of the error model, which is based on the Model super (which was copied from the Item re-write), work. Please have a look and see what the problem is

**Comment by markmacgillivray** [comment]
This is fixed, at the time of this error I had missed out the docstring on the Error class

**Comment by jasonpriem** [comment]
Seems to still (or again) be broken. I had to comment Error.save() out of backend.py (line 193) to get tests to pass.

**Comment by hpiwowar** [comment]
I might have just seen a related problem saving Items that contained a Metrics object.  I added an as_dict to the Metrics object and now an Item with a Metrics object saves properly.  Does Error need a better/different as_dict method, maybe?  

Or might not be related.
