### ISSUE TITLE
document apis with a new developer in mind

### ISSUE THREAD

**Issue by markmacgillivray** [ourresearch/total-impact-core#73]
Add info to api.py to explain how it works, so a new developer can make sense of it.

**Comment by markmacgillivray** [comment]
The API itself has already had docs added, will do more. Also, can add more docs to the code APIs

**Comment by markmacgillivray** [comment]
How much of this has been done, Richard mentioned he was doing more docs at the end of last week, I will check with him.

**Comment by hpiwowar** [comment]
done at http://docs.impactstory.apiary.io/
