### ISSUE TITLE
remove sleep from providers

### ISSUE THREAD

**Issue by jasonpriem** [ourresearch/total-impact-core#80]

**Comment by kevcampb** [comment]
Not 100% sure on what this means, but I've removed all timeout / retry error handling code from the providers. This should still be specificed per-provider in the json config, but the handling of this is now done in the outer controller class 'ProviderMetricsThread'.

Code is on the providerqueue branch.

**Comment by jasonpriem** [comment]
I like the pushing error-handling out of the providers, for sure. But
it seems that the ProvidersAliasThread no longer handles errors at
all. I think that perhaps the process_item method needs to be moved
out of the ProviderMetricsThread and up into the QueueConsumer thread,
so that both of the ProviderThreads can use it?

On Thu, Apr 12, 2012 at 9:18 AM, Kevin Campbell
reply@reply.github.com
wrote:

> Not 100% sure on what this means, but I've removed all timeout / retry error handling code from the providers. This should still be specificed per-provider in the json config, but the handling of this is now done in the outer controller class 'ProviderMetricsThread'.
> 
> Code is on the providerqueue branch.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/total-impact/total-impact-core/issues/80#issuecomment-5090663

## 

Jason Priem
UNC Royster Scholar
School of Information and Library Science
University of North Carolina at Chapel Hill

**Comment by kevcampb** [comment]
I've not really done much with the Alias thread, I was waiting for results
from today's discussion. From that discussion, it should effectively be the
same as the Metrics thread, but processing a sequence of operations rather
than a single call to metrics.

Should have that done early tomorrow.

K

On Fri, Apr 13, 2012 at 12:01 AM, Jason Priem <
reply@reply.github.com

**Comment by jasonpriem** [comment]
Kevin, do you think this one is ready to close now?

**Comment by kevcampb** [comment]
Sleep will go from the providers as part of the cleanup / rewrite. Will make that a larger task.

**Comment by jasonpriem** [comment]
perfect.

On Fri, Apr 27, 2012 at 5:44 AM, Kevin Campbell <
reply@reply.github.com

> wrote:
> 
> Sleep will go from the providers as part of the cleanup / rewrite. Will
> make that a larger task.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/total-impact/total-impact-core/issues/80#issuecomment-5378149

## 

Jason Priem
UNC Royster Scholar
School of Information and Library Science
University of North Carolina at Chapel Hill
