### ISSUE TITLE
replace Item with Alias object where appropriate

### ISSUE THREAD

**Issue by jasonpriem** [ourresearch/total-impact-core#81]
A lot of places we're passing around Items when we're actually dealing with Alias objects ( in the Queues, in the Provider.metrics() params). Fix.

**Comment by kevcampb** [comment]
This is superceeded by #98

We'll be dropping the Models entirely here.

**Comment by jasonpriem** [comment]
yep, sounds good.

On Fri, Apr 27, 2012 at 5:57 AM, Kevin Campbell <
reply@reply.github.com

> wrote:
> 
> This is superceeded by #98
> 
> We'll be dropping the Models entirely here.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/total-impact/total-impact-core/issues/81#issuecomment-5378355

## 

Jason Priem
UNC Royster Scholar
School of Information and Library Science
University of North Carolina at Chapel Hill
