### ISSUE TITLE
test_alias_queue hangs

### ISSUE THREAD

**Issue by hpiwowar** [ourresearch/total-impact-core#90]
test_alias_queue is stalling, looping on the database forever. The problem is triggered by line 70, 
  alias_thread.run()

Bug may have been initiated by the cleanup in commit cd606f90645284ac03215a380fcd390a1d5e6d2e... this commit removed run_once, amongst other things.  

Putting a @nottest on the test because now it hangs all tests.

**Comment by kevcampb** [comment]
I'll have a look at this. I assumed integration tests weren't in use when I committed to master. The aliases thread wasn't functional before my last commit, it didn't do the right things.

**Comment by kevcampb** [comment]
Now resolved. I've adding run_once back in to the alias thread, as that had been removed on the refactor.
