### ISSUE TITLE
standardize on run() or start()

### ISSUE THREAD

**Issue by hpiwowar** [ourresearch/total-impact-core#92]
It seems that in some places we define run() and in others we call start().  Guessing we mean these to be the same thing?  Tried changing them all to start but then 
test_09_alias_stopped
hung.  Leaving it as an outstanding issue for now.

**Comment by kevcampb** [comment]
Run will run the thread's run method in the current thread's context and block until the run method completes. Start will create a new thread and then run the run method in that thread's context.

We're probably correct in what we're doing, as it'd be hard it mix up the calls in the tests and have the tests complete.

**Comment by hpiwowar** [comment]
cool, my bad, I misunderstood.  If I can think of something to rename one of them so the distinction is more clear I'll do that.  Thanks!
